### ISSUE TITLE
Configuración Variables de Entorno

### ISSUE THREAD

**Issue by carlosyllana** [rogermoga/GuardaAlumnos#4]
Crear carpeta script con el nombre de variables.
setx txtFile "alumno.txt"
setx jsonFile "alumno.json"
setx xmlFile "alumno.xml"

**Comment by rogermoga** [comment]
Hecho.

Solamente no hemos conseguido que se ejecute el .bat con las variables de entorno en acciones antes de la compilación. Abro una issue en relacion a eso
